services:
  tamikabot:
    build: .
    image: tamikabot:latest
    # restart: unless-stopped
    privileged: true
    ulimits:
      nproc: 65535
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./bot/db/:/opt/app/bot/db/
    env_file:
      - .env