services:
  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
    restart: unless-stopped
    init: true
    ports:
      - "4416:4416"

  tamikabot:
    image: leersma/tamikabot:latest
    restart: unless-stopped
    privileged: true
    ulimits:
      nproc: 65535
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./bot/db/:/opt/app/bot/db/
      - ./cookies.txt:/opt/app/cookies.txt:ro
    env_file:
      - .env
    depends_on:
      - bgutil-provider